import Link from "next/link";
import { BrandLogo } from "@/components/BrandLogo";
import { ScrollReveal } from "@/components/ScrollReveal";

const agents = [
  { name: "IT", label: "Systems and access", detail: "Devices, accounts, software, and connectivity.", tone: "blue" },
  { name: "Facilities", label: "The physical workplace", detail: "Rooms, equipment, maintenance, and supplies.", tone: "purple" },
  { name: "Security", label: "Sensitive by design", detail: "Risk-aware handling with approval built in.", tone: "pink" },
];

export default function Home() {
  return (
    <main className="landing-page overflow-hidden">
      <ScrollReveal />
      <header className="landing-nav">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8">
          <Link href="/" className="pressable flex items-center gap-2.5" aria-label="OfficeFlow AI home">
            <BrandLogo className="size-20 sm:size-22" priority />
            <span className="text-lg font-black tracking-tight text-slate-950 sm:text-xl">OfficeFlow <span className="brand-text">AI</span></span>
          </Link>
          <nav className="flex items-center gap-2 text-sm font-bold" aria-label="Public navigation">
            <Link href="#how-it-works" className="pressable hidden rounded-lg px-3 py-2 text-slate-600 transition hover:bg-white hover:text-slate-950 sm:inline-flex">How it works</Link>
            <Link href="/login" className="pressable rounded-lg px-3 py-2 text-slate-700 transition hover:bg-white hover:text-blue-700">Sign in</Link>
            <Link href="/register" className="pressable brand-gradient rounded-lg px-3.5 py-2.5 !text-white shadow-lg shadow-blue-200/60 transition hover:-translate-y-0.5 hover:shadow-xl focus:outline-none focus:ring-4 focus:ring-blue-200">Get started</Link>
          </nav>
        </div>
      </header>

      <section className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 pb-12 pt-8 lg:grid-cols-[.9fr_1.1fr] lg:gap-10 lg:px-8 lg:pb-12 lg:pt-12">
        <div className="relative z-10 max-w-2xl">
          <p className="landing-reveal landing-delay-1 mb-5 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/75 px-3.5 py-2 text-xs font-black uppercase tracking-[.18em] text-blue-700 shadow-sm shadow-blue-100"><span className="size-2 rounded-full bg-blue-600 shadow-[0_0_0_4px_rgba(37,99,235,.12)]" /> Intelligent workplace support</p>
          <h1 className="landing-reveal landing-delay-2 max-w-xl text-5xl font-black leading-[.98] tracking-[-.055em] text-slate-950 sm:text-7xl lg:text-[5.4rem]">Your office.<br /><span className="brand-text">Smarter.</span></h1>
          <p className="landing-reveal landing-delay-3 mt-7 max-w-xl text-lg leading-8 text-slate-600 sm:text-xl">Turn natural-language employee requests into intelligently routed, actionable tickets. OfficeFlow AI brings the right team into focus before the work gets stuck.</p>
          <div className="landing-reveal landing-delay-4 mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="pressable brand-gradient inline-flex h-14 items-center justify-center rounded-xl px-6 text-sm font-black text-white shadow-xl shadow-blue-200/70 transition hover:-translate-y-1 hover:shadow-2xl focus:outline-none focus:ring-4 focus:ring-blue-200">Start flowing <span className="ml-2 text-lg">-&gt;</span></Link><Link href="/login" className="pressable inline-flex h-14 items-center justify-center rounded-xl border border-slate-200 bg-white/80 px-6 text-sm font-black text-slate-800 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:text-blue-700 focus:outline-none focus:ring-4 focus:ring-blue-100">Sign in to workspace</Link></div>
          <div className="landing-reveal landing-delay-5 mt-10 flex flex-wrap gap-x-6 gap-y-3 text-xs font-bold text-slate-500"><span className="flex items-center gap-2"><span className="text-blue-600">01</span> AI understood</span><span className="flex items-center gap-2"><span className="text-purple-600">02</span> Team routed</span><span className="flex items-center gap-2"><span className="text-rose-600">03</span> Work resolved</span></div>
        </div>

        <div className="landing-reveal landing-delay-3 relative min-h-[440px] lg:min-h-[500px]" aria-label="OfficeFlow AI routes an employee request to specialized agents">
          <div className="workflow-halo" /><div className="workflow-grid" /><div className="workflow-line workflow-line-main" /><div className="workflow-line workflow-line-left" /><div className="workflow-line workflow-line-center" /><div className="workflow-line workflow-line-right" /><div className="workflow-line workflow-line-approval" />
          <div className="workflow-card workflow-request"><span className="workflow-icon bg-blue-50 text-blue-700">+</span><div><p className="text-[10px] font-black uppercase tracking-[.16em] text-slate-400">Employee request</p><p className="mt-1 text-sm font-bold text-slate-900">My laptop and desk setup need help</p></div></div>
          <div className="workflow-orchestrator"><div className="workflow-orb"><span className="absolute inset-2 rounded-full border border-white/30" /><span className="relative text-xl font-black text-white">OF</span></div><p className="mt-3 text-center text-xs font-black uppercase tracking-[.16em] text-slate-700">AI Orchestrator</p><p className="mt-1 text-center text-[11px] font-semibold text-slate-500">Understands. Splits. Routes.</p></div>
          <div className="workflow-agent workflow-agent-it"><span className="workflow-icon bg-blue-600 text-white">IT</span><div><p className="text-sm font-black text-slate-900">IT agent</p><p className="text-[11px] font-semibold text-slate-500">Device access</p></div></div><div className="workflow-agent workflow-agent-facilities"><span className="workflow-icon bg-purple-600 text-white">F</span><div><p className="text-sm font-black text-slate-900">Facilities</p><p className="text-[11px] font-semibold text-slate-500">Desk setup</p></div></div><div className="workflow-agent workflow-agent-security"><span className="workflow-icon bg-rose-600 text-white">S</span><div><p className="text-sm font-black text-slate-900">Security</p><p className="text-[11px] font-semibold text-slate-500">Risk check</p></div></div>
          <div className="workflow-approval"><span className="grid size-8 place-items-center rounded-lg bg-rose-50 text-rose-600">!</span><div><p className="text-xs font-black text-slate-900">Human approval</p><p className="text-[10px] font-semibold text-slate-500">Only when it matters</p></div><span className="ml-auto size-2 rounded-full bg-emerald-500" /></div>
        </div>
      </section>

      <section className="border-y border-slate-200/80 bg-white/65 py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="max-w-2xl"><p className="section-kicker">The right context, every time</p><h2 className="section-title">One request.<br /><span className="brand-text">Multiple agents.</span></h2><p className="section-copy">Employees speak naturally. OfficeFlow AI identifies the moving parts, creates the work, and gives each team a clear next action.</p></div><div className="mt-12 grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="routing-example rounded-3xl border border-slate-200 bg-slate-950 p-6 text-white shadow-2xl shadow-slate-200/60 sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[.18em] text-blue-300">Live request understanding</span><span className="flex items-center gap-2 text-[11px] font-bold text-emerald-300"><span className="size-2 rounded-full bg-emerald-400" /> Routed</span></div><p className="mt-8 max-w-lg text-2xl font-bold leading-tight sm:text-3xl">“I need a new monitor at my desk, and my VPN keeps disconnecting.”</p><div className="mt-10 grid gap-3 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-xs font-black text-blue-300">IT request</p><p className="mt-1 text-sm font-semibold text-slate-200">VPN troubleshooting</p></div><span className="hidden text-xl text-slate-500 sm:block">+</span><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-xs font-black text-purple-300">Facilities request</p><p className="mt-1 text-sm font-semibold text-slate-200">Monitor provisioning</p></div></div></div><div className="grid gap-4 sm:grid-cols-3 lg:grid-cols-1">{agents.map((agent) => <div key={agent.name} className={`agent-row agent-${agent.tone} rounded-2xl border bg-white p-5 transition hover:-translate-y-1 hover:shadow-lg`}><div className="flex items-center gap-3"><span className={`agent-mark agent-mark-${agent.tone}`}>{agent.name === "Facilities" ? "F" : agent.name[0]}</span><div><p className="font-black text-slate-900">{agent.name}</p><p className="text-xs font-bold text-slate-400">{agent.label}</p></div></div><p className="mt-3 text-sm leading-6 text-slate-600">{agent.detail}</p></div>)}</div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="grid items-end gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="section-kicker">Operational coverage</p><h2 className="section-title">Built for real office operations.</h2></div><p className="section-copy mb-1 max-w-xl">A focused helpdesk for the work people need done every day, with specialized agents that understand the stakes of each request.</p></div><div className="mt-12 grid gap-4 md:grid-cols-3">{agents.map((agent, index) => <div key={agent.name} className={`operation-card operation-${agent.tone} rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-2 hover:shadow-xl`}><span className="text-xs font-black tracking-[.2em] text-slate-400">0{index + 1}</span><div className={`mt-16 h-1 w-14 rounded-full agent-bar-${agent.tone}`} /><h3 className="mt-5 text-2xl font-black text-slate-950">{agent.name}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{agent.detail} Keep the queue moving with structured ownership from the first message.</p><span className="mt-7 inline-flex text-xs font-black uppercase tracking-[.14em] text-slate-400">Specialized agent</span></div>)}</div></section>

      <section className="border-y border-slate-200/80 bg-slate-950 py-20 text-white sm:py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="section-kicker text-blue-300">Guardrails that feel human</p><h2 className="mt-4 max-w-lg text-4xl font-black leading-tight tracking-tight sm:text-5xl">AI + human oversight, in the right order.</h2><p className="mt-6 max-w-md leading-7 text-slate-400">High-risk security actions never disappear into automation. OfficeFlow AI detects risk and pauses the workflow until a security admin can make the call.</p></div><div className="approval-flow rounded-3xl border border-white/10 bg-white/[.06] p-5 sm:p-8"><div className="grid gap-3 sm:grid-cols-5 sm:items-center">{["Request", "Risk detected", "Approval required", "Security admin", "Approved / rejected"].map((step, index) => <div key={step} className="approval-step flex items-center gap-3 sm:block sm:text-center"><span className={`mx-auto grid size-11 shrink-0 place-items-center rounded-xl border text-sm font-black ${index === 2 ? "border-rose-400/50 bg-rose-500/15 text-rose-300" : "border-white/10 bg-white/10 text-blue-200"}`}>{index + 1}</span><p className="text-xs font-bold leading-5 text-slate-300 sm:mt-3">{step}</p>{index < 4 && <span className="hidden text-slate-600 sm:block">-&gt;</span>}</div>)}</div></div></div></div></section>

      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="text-center"><p className="section-kicker">A calmer operating rhythm</p><h2 className="section-title">How it works</h2></div><div className="relative mt-14 grid gap-8 md:grid-cols-4">{["Employee submits", "AI understands", "Agents handle", "People protect"].map((step, index) => <div key={step} className="relative text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-slate-950 text-lg font-black text-white shadow-lg shadow-slate-200">0{index + 1}</span><h3 className="mt-5 font-black text-slate-950">{step}</h3><p className="mx-auto mt-2 max-w-[190px] text-sm leading-6 text-slate-500">{["Describe the need in your own words.", "Intent and urgency become clear.", "The right team gets actionable context.", "Sensitive actions wait for a human."][index]}</p>{index < 3 && <span className="step-connector" aria-hidden="true">-&gt;</span>}</div>)}</div></section>

      <section className="px-5 pb-10 lg:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-gradient-to-br from-blue-600 via-purple-600 to-rose-600 px-6 py-14 text-center text-white shadow-2xl shadow-purple-200/60 sm:px-12 sm:py-20"><p className="text-xs font-black uppercase tracking-[.2em] text-white/70">The workplace, in flow</p><h2 className="mx-auto mt-4 max-w-2xl text-4xl font-black tracking-tight sm:text-6xl">Make your workplace flow smarter.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-white/80">Give every request a clear path forward, from the first sentence to the final resolution.</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><Link
  href="/register"
  className="pressable rounded-xl bg-gradient-to-r from-blue-500 via-purple-500 to-rose-500 px-6 py-3.5 text-sm font-black text-white shadow-lg transition hover:-translate-y-1 hover:shadow-xl"
>
  Get started
</Link><Link href="/login" className="pressable rounded-xl border border-white/30 bg-white/10 px-6 py-3.5 text-sm font-black text-white transition hover:-translate-y-1 hover:bg-white/20">Sign in</Link></div></div></section>

      <footer className="landing-footer mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><Link href="/" className="pressable flex items-center gap-2.5"><BrandLogo className="size-14" /><span className="font-black text-slate-900">OfficeFlow <span className="brand-text">AI</span></span></Link><p>Intelligent support for the work behind the work.</p><p className="font-semibold">© 2026 OfficeFlow AI</p></footer>
    </main>
  );
}
