"use client";

import Link from "next/link";
import { useState } from "react";
import { label, priorityStyles, statusStyles, Ticket } from "./TicketCard";

export function TicketTable({ tickets, admin = false, adminPath = false, onUpdated }: { tickets: Ticket[]; admin?: boolean; adminPath?: boolean; onUpdated?: () => void }) {
	const [updating, setUpdating] = useState<number | null>(null);
	async function updateTicket(id: number, changes: Record<string, string | null>) {
		setUpdating(id);
		try { await fetch(`/api/tickets/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(changes) }); onUpdated?.(); } finally { setUpdating(null); }
	}
	if (!tickets.length) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><p className="font-bold text-slate-800">No tickets yet</p><p className="mt-1 text-sm text-slate-500">Your submitted workplace requests will appear here.</p></div>;
	return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[1.5fr_.75fr_.75fr_.8fr_1fr] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[11px] font-bold uppercase tracking-wider text-slate-400 md:grid"><span>Ticket</span><span>Team</span><span>Priority</span><span>Status</span><span>Created</span></div>{tickets.map((ticket) => <div key={ticket.id} className="grid gap-3 border-b border-slate-100 px-5 py-4 last:border-0 md:grid-cols-[1.5fr_.75fr_.75fr_.8fr_1fr] md:items-center md:gap-4"><div><Link href={`${adminPath ? "/admin/tickets" : "/tickets"}/${ticket.id}`} className="font-bold text-slate-900 hover:text-blue-700">{ticket.title}</Link><p className="mt-1 text-xs text-slate-400">#{ticket.id} · {ticket.category}</p>{admin && <input aria-label={`Assign ticket ${ticket.id}`} defaultValue={ticket.assignedTo ?? ""} placeholder="Unassigned" onBlur={(event) => void updateTicket(ticket.id, { assignedTo: event.target.value.trim() || null })} className="mt-2 w-full max-w-40 border-b border-slate-200 bg-transparent text-xs text-slate-600 outline-none placeholder:text-slate-400 focus:border-blue-500" />}</div><span className="text-sm text-slate-600">{ticket.assignedTeam}</span>{admin ? <select aria-label={`Update priority for ticket ${ticket.id}`} disabled={updating === ticket.id} value={ticket.priority} onChange={(event) => void updateTicket(ticket.id, { priority: event.target.value })} className={`w-fit border-0 bg-transparent text-sm font-bold outline-none ${priorityStyles[ticket.priority] || "text-slate-500"}`}><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option><option value="CRITICAL">Critical</option></select> : <span className={`text-sm font-bold ${priorityStyles[ticket.priority] || "text-slate-500"}`}>{label(ticket.priority)}</span>}{admin ? <select aria-label={`Update status for ticket ${ticket.id}`} disabled={updating === ticket.id} value={ticket.status} onChange={(event) => void updateTicket(ticket.id, { status: event.target.value })} className={`w-fit rounded-full border-0 px-2.5 py-1 text-xs font-bold outline-none ${statusStyles[ticket.status] || "bg-slate-100"}`}><option value="OPEN">Open</option><option value="ASSIGNED">Assigned</option><option value="IN_PROGRESS">In progress</option><option value="AWAITING_APPROVAL">Awaiting approval</option><option value="RESOLVED">Resolved</option><option value="REJECTED">Rejected</option></select> : <span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${statusStyles[ticket.status] || "bg-slate-100 text-slate-600"}`}>{label(ticket.status)}</span>}<span className="text-sm text-slate-500">{new Date(ticket.createdAt).toLocaleDateString()}</span></div>)}</div>;
}
